title: Aggregation based ensemble classifier vs neural networks models for recognizing phishing attacks
description: WOJCIECH GAŁKA, JAN G. BAZAN, URSZULA BENTKOWSKA, KAMIL SZWED, MARCIN MRUKOWICZ, PAWEŁ DRYGAŚ, LECH ZARĘBA, MARCIN SZPYRKA, PIOTR SUSZALSKI, SEBASTIAN OBARA
theme: minima
