title: Aggregation based ensemble classifier vs neural networks models for recognizing phishing attacks
description: WOJCIECH GAŁKA, JAN G. BAZAN, URSZULA BENTKOWSKA, KAMIL SZWED, MARCIN MRUKOWICZ, PAWEŁ DRYGAŚ, LECH ZARĘBA, MARCIN SZPYRKA, PIOTR SUSZALSKI, SEBASTIAN OBARA
theme: just-the-docs

url: https://YOUR-USERNAME.github.io/YOUR-SITE-NAME

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME