
title: Aggregation based ensemble classifier vs neural networks models for recognizing phishing attacks
description: Wojciech Gałka, Jan G. Bazan, Urszula Bentkowska, Kamil Szwed, Marcin Mrukowicz, Paweł Drygaś, Lech Zaręba, Marcin Szpyrka, Piotr Suszalski, Sebastian Obara
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
